spring:
  graphql:
    websocket:
      path: /graphql
      
  data:
    mongodb:
      database: samples-spring-graphql

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


logging:
  level:
    org:
      springframework:
        web: debug
        http: debug
        graphql: debug
        security: debug
      github: debug
    reactor:
      netty: debug